import os
from dotenv import load_dotenv
from utils.classes.Singleton import Singleton

class Settings(metaclass=Singleton):
    ENV = None
    API_KEY = None
    EMAIL_SENDER = None
    EMAIL_SENDER_PASS = None
    EXCEPTION_EMAILS = None
    CONTAINER_NAME = None
    RECOMMENDATIONS_FILE_NAME = None
    APPLICATIONINSIGHTS_CONNECTION_STRING = None
    TEST_EMAIL_FOR_RECOMMENDATIONS = None
    TEST_PRODUCT_FOR_SIMILAR_PRODUCTS = None
    TEST_PRODUCT_FOR_CROSS_SELL = None
    REDIS_USERNAME = None
    HOMEPAGE_RECOMMENDER_REDIS_PASS = None
    SIMILAR_PRODUCTS_RECOMMENDER_REDIS_PASS = None
    CROSS_SELL_RECOMMENDER_REDIS_PASS = None

    def __init__(self):
        load_dotenv()
        self.ENV = os.getenv('ENV')
        self.API_KEY = os.getenv('API_KEY')
        self.EMAIL_SENDER = os.getenv('EMAIL_SENDER')
        self.EMAIL_SENDER_PASS = os.getenv('EMAIL_SENDER_PASS')
        self.EXCEPTION_EMAILS = os.getenv('EXCEPTION_EMAILS')
        self.CONTAINER_NAME = os.getenv('CONTAINER_NAME')
        self.RECOMMENDATIONS_FILE_NAME = os.getenv('RECOMMENDATIONS_FILE_NAME')
        self.APPLICATIONINSIGHTS_CONNECTION_STRING = os.getenv('APPLICATIONINSIGHTS_CONNECTION_STRING')
        self.TEST_EMAIL_FOR_RECOMMENDATIONS = os.getenv('TEST_EMAIL_FOR_RECOMMENDATIONS')
        self.TEST_PRODUCT_FOR_SIMILAR_PRODUCTS = os.getenv('TEST_PRODUCT_FOR_SIMILAR_PRODUCTS')
        self.TEST_PRODUCT_FOR_CROSS_SELL = os.getenv('TEST_PRODUCT_FOR_CROSS_SELL')
        self.REDIS_USERNAME = os.getenv('REDIS_USERNAME')
        self.HOMEPAGE_RECOMMENDER_REDIS_PASS = os.getenv('HOMEPAGE_RECOMMENDER_REDIS_PASS')
        self.SIMILAR_PRODUCTS_RECOMMENDER_REDIS_PASS = os.getenv('SIMILAR_PRODUCTS_RECOMMENDER_REDIS_PASS')
        self.CROSS_SELL_RECOMMENDER_REDIS_PASS = os.getenv('CROSS_SELL_RECOMMENDER_REDIS_PASS')
